const APP='Rolling Wrench AI Command Pro';
const DEFAULTS={rate:135,service:250,tax:7,card:0,rent:1500,insurance:145,electric:250,backend:'https://rolling-wrench-ai-backend.onrender.com',supabase:'https://uxpkqwcmvtqvubibbrek.supabase.co'};
const $=id=>document.getElementById(id);let historyStack=['home'];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function money(n){return '$'+Number(n||0).toFixed(2)}function now(){return new Date().toLocaleString()}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function alertMsg(msg,type='ok'){const a=store.get('alerts',[]);a.unshift({msg,type,date:now()});store.set('alerts',a.slice(0,20));renderAlerts()}
function renderAlerts(){const box=$('alertsBox');if(!box)return;const a=store.get('alerts',[]);box.innerHTML=a.length?a.slice(0,4).map(x=>`⚠ ${esc(x.date)} — ${esc(x.msg)}`).join('\n'):'NO ALERTS';}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active');if(historyStack.at(-1)!==id)historyStack.push(id);window.scrollTo(0,0);renderAll()}
function goBack(){historyStack.pop();show(historyStack.pop()||'home')}
function signIn(){const n=$('loginName').value.trim()||'James Jacobs';localStorage.setItem('signedIn','1');localStorage.setItem('employeeName',n);$('login').classList.add('hide');$('ownerName').value=n;alertMsg('Signed in: '+n)}
function demoSignIn(){ $('loginName').value='James Jacobs'; signIn() }
function loadLogin(){if(localStorage.getItem('signedIn'))$('login').classList.add('hide')}
function settings(){return {...DEFAULTS,...store.get('settings',{})}}
function saveSettings(){const s=settings();s.rate=+$('setRate').value||DEFAULTS.rate;s.backend=$('backendUrl').value||DEFAULTS.backend;s.supabase=$('supabaseUrl').value||DEFAULTS.supabase;s.theme=$('theme').value;s.owner=$('ownerName').value;s.role=$('role').value;store.set('settings',s);setTheme(s.theme);$('settingsOut').textContent='Settings saved. '+now();alertMsg('Settings saved')}
function loadSettings(){const s=settings();$('quoteRate').value=s.rate;$('serviceCall').value=s.service;$('taxRate').value=s.tax;$('cardFee').value=s.card;$('rent').value=s.rent;$('insurance').value=s.insurance;$('electric').value=s.electric;$('backendUrl').value=s.backend;$('supabaseUrl').value=s.supabase;$('setRate').value=s.rate;$('ownerName').value=s.owner||localStorage.getItem('employeeName')||'James Jacobs';$('theme').value=s.theme||'green';setTheme(s.theme||'green')}
function setTheme(t){document.body.classList.remove('green','orange','red','blue','night');document.body.classList.add(t||'green')}
function mode(m){store.set('mode',m);$('modeBadge').textContent=(m==='road'?'ROADSIDE MODE':'SHOP MODE');$('serviceToggle').checked=m==='road';alertMsg((m==='road'?'Roadside':'Shop')+' mode active')}
function saveTruck(){const t={vin:$('vin').value.trim().toUpperCase(),year:$('year').value,make:$('make').value,model:$('model').value,engine:$('engine').value,unit:$('unit').value,mileage:$('mileage').value};store.set('truck',t);alertMsg('Truck saved');renderAll()}
function clearTruck(){['vin','year','make','model','engine','unit','mileage'].forEach(id=>$(id).value='');localStorage.removeItem('truck');renderAll()}
async function decodeVin(){const vin=$('vin').value.trim().toUpperCase();if(!vin)return alert('Enter VIN');$('truckOut').textContent='Decoding VIN...';try{const r=await fetch('https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/'+encodeURIComponent(vin)+'?format=json');const d=(await r.json()).Results?.[0]||{};$('year').value=d.ModelYear||'';$('make').value=d.Make||'';$('model').value=d.Model||'';$('engine').value=d.EngineModel||d.EngineManufacturer||'';saveTruck();$('truckOut').textContent='VIN decoded and saved.'}catch(e){$('truckOut').textContent='VIN decode failed: '+e.message}}
function saveCustomer(){const c={name:$('custName').value,phone:$('custPhone').value,email:$('custEmail').value,address:$('custAddress').value};store.set('customer',c);alertMsg('Customer saved');renderAll()}
function clearCustomer(){['custName','custPhone','custEmail','custAddress'].forEach(id=>$(id).value='');localStorage.removeItem('customer');renderAll()}
const clocks={A:{elapsed:0,running:false,start:0},B:{elapsed:0,running:false,start:0},C:{elapsed:0,running:false,start:0}};
function loadClocks(){Object.assign(clocks,store.get('clocks',clocks));['A','B','C'].forEach(k=>{if($('clock'+k+'Label'))$('clock'+k+'Label').value=clocks[k].label||''})}
function saveClocks(){['A','B','C'].forEach(k=>clocks[k].label=$('clock'+k+'Label')?.value||'');store.set('clocks',clocks)}
function clockMs(k){const c=clocks[k];return c.elapsed+(c.running?(Date.now()-c.start):0)}function hours(k){return clockMs(k)/36e5}
function clockStart(k){const c=clocks[k];if(!c.running){c.running=true;c.start=Date.now();$('clock'+k+'Status').textContent='RUNNING';alertMsg('Clock '+k+' started')}saveClocks();renderClocks()}
function clockPause(k){const c=clocks[k];if(c.running){c.elapsed+=Date.now()-c.start;c.running=false;$('clock'+k+'Status').textContent='PAUSED';alertMsg('Clock '+k+' paused')}saveClocks();renderClocks()}
function clockStop(k){clockPause(k);$('clock'+k+'Status').textContent='STOPPED';alertMsg('Clock '+k+' stopped')}
function clockReset(k){clocks[k]={elapsed:0,running:false,start:0,label:''};saveClocks();renderClocks()}
function clockToInvoice(k){$('quoteHours').value=hours(k).toFixed(2);$('invoiceNotes').value+='\nClock '+k+': '+hours(k).toFixed(2)+' hrs '+money(hours(k)*settings().rate);show('invoice')}
function renderClocks(){['A','B','C'].forEach(k=>{const ms=clockMs(k),sec=Math.floor(ms/1000),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;const rate=+$('quoteRate')?.value||settings().rate;$('clock'+k+'Time').textContent=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':');$('clock'+k+'Money').textContent=money(ms/36e5*rate);$('clock'+k+'Status').textContent=clocks[k].running?'RUNNING':(ms?'PAUSED':'READY')})}
function lookupPart(){const q=$('partQuery').value.trim();if(!q)return alert('Enter part');$('partsOut').innerHTML=`Searching: ${esc(q)}\n\nUse supplier buttons for live web searches. Add price manually after supplier quote.`;tryBackend('/api/parts',{q}).then(x=>{if(x)$('partsOut').textContent=JSON.stringify(x,null,2)}).catch(()=>{})}
function supplier(s){const q=encodeURIComponent($('partQuery').value||'diesel truck parts');const urls={fleetpride:`https://www.google.com/search?q=site:fleetpride.com+${q}`,napa:`https://www.napaonline.com/en/search?text=${q}`,oreilly:`https://www.oreillyauto.com/search?q=${q}`,truckpro:`https://www.google.com/search?q=site:truckpro.com+${q}`,google:`https://www.google.com/search?q=${q}`,dealer:`https://www.google.com/maps/search/heavy+duty+truck+parts+${q}`};window.open(urls[s],'_blank')}
function addPartLine(){const q=$('partQuery').value.trim();if(!q)return;const cur=+$('quoteParts').value||0;$('quoteParts').value=cur; $('quoteDesc').value+='\nPart: '+q; alertMsg('Part added to quote notes')}
function clearParts(){$('partQuery').value='';$('partsOut').textContent=''}
async function scanImage(e){const f=e.target.files?.[0];if(!f)return;const p=$('scanPreview');p.src=URL.createObjectURL(f);p.style.display='block';$('scanOut').textContent='Reading image...';try{if(!window.Tesseract)throw new Error('OCR library not loaded');const r=await Tesseract.recognize(f,'eng');$('scanText').value=r.data.text||'';$('scanOut').textContent='OCR complete.'}catch(err){$('scanOut').textContent='OCR failed: '+err.message}}
function parseScan(){const text=$('scanText').value;const price=(text.match(/\$?\s*(\d+\.\d{2})/g)||[]).pop()||'';const part=(text.match(/\b[A-Z0-9-]{5,18}\b/i)||[''])[0];$('scanOut').textContent=`PART: ${part}\nPRICE: ${price}\nTYPE: ${$('scanType').value}`}
function scanToInvoice(){$('invoiceNotes').value+='\nSCAN:\n'+$('scanOut').textContent;show('invoice')}
function clearScan(){$('scanText').value='';$('scanOut').textContent='';$('scanPreview').style.display='none'}
function calcTotals(){const h=+$('quoteHours').value||0,r=+$('quoteRate').value||settings().rate,p=+$('quoteParts').value||0,svc=$('serviceToggle').checked?(+$('serviceCall').value||0):0,taxPct=+$('taxRate').value||0,cardPct=+$('cardFee').value||0;const labor=h*r,sub=labor+p+svc,tax=sub*taxPct/100,card=(sub+tax)*cardPct/100,total=sub+tax+card;return{h,r,p,svc,labor,sub,tax,card,total}}
function docHeader(title){const c=store.get('customer',{}),t=store.get('truck',{});return `<h3>${title}</h3><b>Rolling Wrench Diesel LLC</b><br>James Jacobs • 260-502-6222<br>www.rollingwrenchdiesel.com<hr><b>Customer:</b> ${esc(c.name||'')} ${esc(c.phone||'')}<br><b>Truck:</b> ${esc([t.year,t.make,t.model,t.engine].filter(Boolean).join(' '))}<br><b>VIN:</b> ${esc(t.vin||'')}<br><b>Date:</b> ${now()}<hr>`}
function buildQuote(){const x=calcTotals();$('quoteOut').innerHTML=docHeader('QUOTE')+`<b>Job:</b> ${esc($('quoteJob').value)}<br><b>Work:</b><br>${esc($('quoteDesc').value).replace(/\n/g,'<br>')}<hr>Labor: ${money(x.labor)}<br>Service Call: ${money(x.svc)}<br>Parts: ${money(x.p)}<br>Tax: ${money(x.tax)}<br>Card Fee: ${money(x.card)}<h3>Total: ${money(x.total)}</h3><small>Quote subject to inspection, parts availability, and customer approval.</small>`;store.set('lastQuote',x);updateFinance();alertMsg('Quote built')}
function writeProfessional(type){const map={quote:'quoteDesc',workorder:'woWork'};const id=map[type]||'invoiceNotes';const v=$(id).value;$(id).value='Work to be performed professionally and verified upon completion. '+v;alertMsg('Professional wording added')}
function quoteToInvoice(){buildQuote();$('invoiceNotes').value=$('quoteOut').innerText;show('invoice')}
function buildWorkOrder(){$('woOut').innerHTML=docHeader('WORK ORDER')+`<b>Complaint:</b><br>${esc($('woComplaint').value).replace(/\n/g,'<br>')}<hr><b>Diagnosis:</b><br>${esc($('woDiagnosis').value).replace(/\n/g,'<br>')}<hr><b>Work Performed:</b><br>${esc($('woWork').value).replace(/\n/g,'<br>')}`;alertMsg('Work order built')}
function workToInvoice(){buildWorkOrder();$('invoiceNotes').value=$('woOut').innerText;show('invoice')}
function sigData(){return $('sigCanvas').toDataURL('image/png')}
function buildInvoice(){const x=calcTotals();const copy=$('invoiceType').value;let html=docHeader('INVOICE - '+copy)+`<b>Notes / Work:</b><br>${esc($('invoiceNotes').value||$('quoteDesc').value).replace(/\n/g,'<br>')}<hr>Labor: ${money(x.labor)}<br>Service Call: ${money(x.svc)}<br>Parts: ${money(x.p)}<br>Tax: ${money(x.tax)}<br>Card Fee: ${money(x.card)}<h3>Total Due: ${money(x.total)}</h3><b>Customer Signature:</b><br><img src="${sigData()}" style="max-width:100%;border:1px solid #111">`;$('invoiceOut').innerHTML=html;store.set('lastInvoice',{total:x.total,date:now(),html});updateFinance();alertMsg('Invoice built')}
function textInvoice(){buildInvoice();const c=store.get('customer',{});const txt=encodeURIComponent($('invoiceOut').innerText);location.href=`sms:${c.phone||''}?&body=${txt}`}
function saveInvoice(){buildInvoice();const list=store.get('invoices',[]);list.unshift(store.get('lastInvoice',{}));store.set('invoices',list);alertMsg('Invoice saved');updateFinance()}
function addSchedule(){const list=store.get('schedule',[]);list.unshift({date:$('schDate').value,time:$('schTime').value,customer:$('schCustomer').value,job:$('schJob').value});store.set('schedule',list);renderSchedule();alertMsg('Schedule added')}
function renderSchedule(){const l=store.get('schedule',[]);$('scheduleOut').innerHTML=l.length?l.map(x=>`${esc(x.date)} ${esc(x.time)} — ${esc(x.customer)} — ${esc(x.job)}`).join('\n'):'NO SCHEDULED WORK'}
function clearSchedule(){store.set('schedule',[]);renderSchedule()}
function updateFinance(){const inv=store.get('invoices',[]).reduce((s,i)=>s+(+i.total||0),0);const h=['A','B','C'].reduce((s,k)=>s+hours(k),0),labor=h*settings().rate;const over=(+$('rent').value||0)+ (+$('insurance').value||0)+ (+$('electric').value||0)+ (+$('otherExpense').value||0);$('finLabor').textContent=money(labor);$('finParts').textContent=money(+$('quoteParts').value||0);$('finInvoices').textContent=money(inv);$('finBreakEven').textContent=money(over)}
async function testBackend(){const out=$('settingsOut');out.textContent='Testing backend...';try{const base=(settings().backend||'').replace(/\/$/,'');const r=await fetch(base+'/api/health',{method:'GET'});out.textContent='Backend health response: '+r.status}catch(e){out.textContent='Backend test failed: '+e.message}}
async function tryBackend(path,body){const url=(settings().backend||'').replace(/\/$/,'')+path;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('backend '+r.status);return r.json()}
function resetApp(){if(confirm('Reset local app data?')){localStorage.clear();location.reload()}}
function renderAll(){const t=store.get('truck',{}),c=store.get('customer',{});$('activeTruckBox').innerHTML=t.vin?`${esc(t.unit||'')} ${esc(t.year||'')} ${esc(t.make||'')} ${esc(t.model||'')}<br>${esc(t.engine||'')}<br>${esc(t.vin||'')}`:'NO ACTIVE TRUCK';$('activeCustomerBox').innerHTML=c.name?`${esc(c.name)}<br>${esc(c.phone||'')}<br>${esc(c.email||'')}`:'NO CUSTOMER SELECTED';renderClocks();renderAlerts();renderSchedule();updateFinance()}
function loadFields(){const t=store.get('truck',{}),c=store.get('customer',{});Object.entries({vin:t.vin,year:t.year,make:t.make,model:t.model,engine:t.engine,unit:t.unit,mileage:t.mileage,custName:c.name,custPhone:c.phone,custEmail:c.email,custAddress:c.address}).forEach(([k,v])=>{if($(k))$(k).value=v||''})}
function initSig(){const canvas=$('sigCanvas'),ctx=canvas.getContext('2d');ctx.lineWidth=4;ctx.lineCap='round';let draw=false;function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}}function start(e){draw=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!draw)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function end(){draw=false}canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end)}
function clearSignature(){const c=$('sigCanvas');c.getContext('2d').clearRect(0,0,c.width,c.height)}
window.addEventListener('DOMContentLoaded',()=>{loadLogin();loadSettings();loadClocks();loadFields();initSig();renderAll();setInterval(()=>{renderClocks();updateFinance();saveClocks()},1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})});
