const DEFAULTS={shop:'Rolling Wrench Diesel LLC',phone:'260-502-6222',web:'www.rollingwrenchdiesel.com',backend:'https://rolling-wrench-ai-backend.onrender.com',supabaseUrl:'https://uxpkqwcmvtqvubibbrek.supabase.co',supabaseKey:'',rate:135,service:250,markup:15,tax:7,card:0,theme:'orange',mode:'shop'};
const $=id=>document.getElementById(id);
const money=n=>'$'+Number(n||0).toFixed(2);
const clean=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let screen='home', historyStack=[];
function getSettings(){return {...DEFAULTS,...JSON.parse(localStorage.getItem('rw_settings')||'{}')}}
function setSettings(s){localStorage.setItem('rw_settings',JSON.stringify({...getSettings(),...s}))}
function show(id){if(!$(id))return;if(screen!==id)historyStack.push(screen);screen=id;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');closeMenu();scrollTo(0,0);renderAll()}
function back(){const last=historyStack.pop(); if(last&&$(last)){screen=last;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(last).classList.add('active');renderAll();}else show('home')}
function openMenu(){$('menu').classList.add('open')} function closeMenu(){$('menu').classList.remove('open')}
function setMode(m){setSettings({mode:m});renderAll()}
function storage(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function truck(){return storage('rw_truck',{})} function customer(){return storage('rw_customer',{})} function parts(){return storage('rw_parts',[])}
function renderDash(){const t=truck(),c=customer(),s=getSettings();document.body.className=s.theme==='orange'?'':'theme-'+s.theme;['shopModeBtn','roadModeBtn'].forEach(id=>$(id)?.classList.remove('active'));$(s.mode+'ModeBtn')?.classList.add('active');$('dashVin').textContent=t.vin||'NO ACTIVE TRUCK';$('dashYear').textContent=t.year||'—';$('dashMake').textContent=t.make||'—';$('dashModel').textContent=t.model||'—';$('dashEngine').textContent=t.engine||'—';$('dashCustomer').textContent=c.company||'NO CUSTOMER SELECTED';$('dashPhone').textContent=c.phone||'—'}
function saveTruck(){const t={vin:$('vin').value.trim().toUpperCase(),unit:$('unit').value.trim(),year:$('year').value.trim(),make:$('make').value.trim(),model:$('model').value.trim(),engine:$('engine').value.trim(),esn:$('esn').value.trim(),cpl:$('cpl').value.trim()};save('rw_truck',t);$('truckOut').textContent='Truck saved.';renderAll()}
function loadTruckFields(){const t=truck();['vin','unit','year','make','model','engine','esn','cpl'].forEach(id=>{if($(id))$(id).value=t[id]||''})}
function clearTruck(){localStorage.removeItem('rw_truck');loadTruckFields();$('truckOut').textContent='Truck cleared.';renderAll()}
async function decodeVin(){const vin=$('vin').value.trim().toUpperCase();if(!vin)return alert('Enter VIN.');$('truckOut').textContent='Decoding VIN...';try{const r=await fetch('https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/'+encodeURIComponent(vin)+'?format=json');const data=await r.json();const d=data.Results?.[0]||{};$('year').value=d.ModelYear||$('year').value;$('make').value=d.Make||$('make').value;$('model').value=d.Model||$('model').value;$('engine').value=d.EngineModel||d.EngineManufacturer||$('engine').value;$('truckOut').textContent='VIN decoded. Verify heavy truck engine/trans before ordering parts.';saveTruck()}catch(e){$('truckOut').textContent='VIN decode failed: '+e.message}}
function saveCustomer(){const c={company:$('custCompany').value.trim(),contact:$('custContact').value.trim(),phone:$('custPhone').value.trim(),email:$('custEmail').value.trim(),address:$('custAddress').value.trim(),notes:$('custNotes').value.trim()};save('rw_customer',c);$('customerOut').textContent='Customer saved.';renderAll()}
function loadCustomerFields(){const c=customer();[['custCompany','company'],['custContact','contact'],['custPhone','phone'],['custEmail','email'],['custAddress','address'],['custNotes','notes']].forEach(([id,k])=>{if($(id))$(id).value=c[k]||''})}
function clearCustomer(){localStorage.removeItem('rw_customer');loadCustomerFields();$('customerOut').textContent='Customer cleared.';renderAll()}
const clockState=()=>storage('rw_clocks',{A:{elapsed:0,running:false,paused:false,last:null},B:{elapsed:0,running:false,paused:false,last:null},C:{elapsed:0,running:false,paused:false,last:null}});
function saveClocks(c){save('rw_clocks',c)}
function clockMs(x){let e=x.elapsed||0;if(x.running&&x.last)e+=Date.now()-x.last;return e}
function fmt(ms){const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return [h,m,s].map(v=>String(v).padStart(2,'0')).join(':')}
function clockStart(k){let c=clockState();c[k].running=true;c[k].paused=false;c[k].last=Date.now();saveClocks(c);renderClocks()}
function clockPause(k){let c=clockState();if(c[k].running){c[k].elapsed=clockMs(c[k]);c[k].running=false;c[k].paused=true;c[k].last=null;saveClocks(c)}renderClocks()}
function clockStop(k){let c=clockState();if(c[k].running)c[k].elapsed=clockMs(c[k]);c[k].running=false;c[k].paused=false;c[k].last=null;saveClocks(c);renderClocks()}
function clockReset(k){let c=clockState();c[k]={elapsed:0,running:false,paused:false,last:null};saveClocks(c);renderClocks()}
function sendClock(k){let hrs=(clockMs(clockState()[k])/3600000).toFixed(2);if($('invHours'))$('invHours').value=hrs;if($('quoteHours'))$('quoteHours').value=hrs;show('invoice')}
function resetAllClocks(){if(confirm('Clear all clocks?')){localStorage.removeItem('rw_clocks');renderClocks()}}
function renderClocks(){const c=clockState();const mini=Object.keys(c).map(k=>`<div class="clockPill"><b>CLOCK ${k}</b><span>${fmt(clockMs(c[k]))}</span></div>`).join('');if($('clockHome'))$('clockHome').innerHTML=mini;const full=Object.keys(c).map(k=>`<div class="clockCard"><h2>CLOCK ${k}</h2><div class="clockTime">${fmt(clockMs(c[k]))}</div><div class="clockBtns"><button onclick="clockStart('${k}')">START</button><button onclick="clockPause('${k}')">PAUSE</button><button onclick="clockStart('${k}')">RESUME</button><button onclick="clockStop('${k}')">STOP</button><button onclick="sendClock('${k}')">SEND</button><button onclick="clockReset('${k}')">RESET</button></div></div>`).join('');if($('clockFull'))$('clockFull').innerHTML=full}
async function backend(path,payload){const s=getSettings();const url=s.backend.replace(/\/$/,'')+path;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||r.statusText);return d}
async function lookupPart(){const q=$('partQuery').value.trim()||$('partNumber').value.trim();if(!q)return alert('Enter part.');$('partsOut').textContent='Searching...';let msg='';try{const d=await backend('/parts',{query:q,truck:truck()});msg=d.answer||d.message||JSON.stringify(d,null,2)}catch(e){msg='Backend not available. Use supplier buttons or local entry.\n\n'+q}$('partsOut').textContent=msg}
function addPartToJob(){const s=getSettings();const cost=Number($('partCost').value||0),qty=Number($('partQty').value||1),markup=Number($('partMarkup').value||s.markup);const sell=cost*(1+markup/100);const p={desc:$('partQuery').value.trim(),num:$('partNumber').value.trim(),qty,cost,sell,supplier:$('partSupplier').value.trim()};const list=parts();list.push(p);save('rw_parts',list);renderParts();$('partsOut').textContent='Part added.'}
function renderParts(){const list=parts();const html=list.map((p,i)=>`<div class="lineItem"><b>${clean(p.desc||'Part')}</b><br>Part #: ${clean(p.num||'')} | Qty: ${p.qty} | Sell: ${money(Number(p.sell||0)*Number(p.qty||1))}<br><button onclick="removePart(${i})">REMOVE</button></div>`).join('');if($('partsList'))$('partsList').innerHTML=html||''}
function removePart(i){const list=parts();list.splice(i,1);save('rw_parts',list);renderParts()}
function clearParts(){['partQuery','partNumber','partCost','partSupplier'].forEach(id=>$(id).value='');$('partQty').value=1;$('partMarkup').value=getSettings().markup;$('partsOut').textContent=''}
function supplierSearch(w){const q=encodeURIComponent(($('partNumber')?.value||$('partQuery')?.value||'truck parts').trim());const urls={google:`https://www.google.com/search?q=${q}`,fleetpride:`https://www.google.com/search?q=FleetPride+${q}`,napa:`https://www.napaonline.com/en/search?text=${q}`,truckpro:`https://www.google.com/search?q=TruckPro+${q}`,oreilly:`https://www.oreillyauto.com/search?q=${q}`};window.open(urls[w]||urls.google,'_blank')}
function clearScan(){['scanText'].forEach(id=>$(id).value='');$('scanOut').textContent='';$('scanPreview').style.display='none'}
$('scanFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(f){$('scanPreview').src=URL.createObjectURL(f);$('scanPreview').style.display='block'}});
async function runOCR(){const f=$('scanFile').files[0];if(!f)return alert('Add photo.');$('scanOut').textContent='Reading photo...';try{const r=await Tesseract.recognize(f,'eng');$('scanText').value=r.data.text||'';$('scanOut').textContent='Photo read. Check/correct text.'}catch(e){$('scanOut').textContent='OCR failed: '+e.message}}
function parseScan(){const text=$('scanText').value;const part=(text.match(/\b[A-Z]{1,4}[- ]?\d{3,8}[A-Z0-9-]*\b/i)||[])[0]||'';const price=(text.match(/\$?\s?(\d+\.\d{2})/)||[])[1]||'';$('scanOut').textContent=`PART: ${part||'not found'}\nPRICE: ${price||'not found'}`;if(part)$('partNumber').value=part;if(price)$('partCost').value=price}
function scanToParts(){parseScan();show('parts')}
function scanToInvoice(){parseScan(); if($('invDesc'))$('invDesc').value+=(($('invDesc').value?'\n':'')+$('scanText').value.slice(0,500));show('invoice')}
function partTotal(){return parts().reduce((s,p)=>s+(Number(p.sell||0)*Number(p.qty||1)),0)}
function partCostTotal(){return parts().reduce((s,p)=>s+(Number(p.cost||0)*Number(p.qty||1)),0)}
function docContext(){const t=truck(),c=customer();return `${getSettings().shop}\n${getSettings().phone}\n${getSettings().web}\n\nCUSTOMER: ${c.company||''} ${c.phone||''}\nTRUCK: ${t.year||''} ${t.make||''} ${t.model||''} ${t.engine||''}\nVIN: ${t.vin||''}`}
function totals(prefix){const s=getSettings();const h=Number($(prefix+'Hours').value||0),r=Number($(prefix+'Rate').value||s.rate),serviceOn=$(prefix+'ServiceOn').checked,svc=serviceOn?Number($(prefix+'Service').value||s.service):0,travel=Number($(prefix+'Travel').value||0),taxPct=Number($(prefix+'Tax').value||s.tax),cardPct=Number($(prefix+'Card').value||s.card);const labor=h*r,partsSell=partTotal(),subtotal=labor+partsSell+svc+travel,tax=subtotal*(taxPct/100),card=(subtotal+tax)*(cardPct/100),total=subtotal+tax+card;return{h,r,svc,travel,labor,partsSell,subtotal,tax,card,total}}
function partsText(){const list=parts();return list.length?list.map((p,i)=>`${i+1}. ${p.desc||'Part'} ${p.num?`(${p.num})`:''} Qty ${p.qty} — ${money(Number(p.sell||0)*Number(p.qty||1))}`).join('\n'):'No parts added.'}
function buildQuote(){const x=totals('quote'),desc=$('quoteDesc').value;const out=`QUOTE\n${docContext()}\n\nWORK REQUEST:\n${desc}\n\nPARTS:\n${partsText()}\n\nLABOR: ${x.h} hrs x ${money(x.r)} = ${money(x.labor)}\nSERVICE CALL: ${money(x.svc)}\nTRAVEL / MILEAGE: ${money(x.travel)}\nPARTS: ${money(x.partsSell)}\nSUBTOTAL: ${money(x.subtotal)}\nTAX: ${money(x.tax)}\nCARD FEE: ${money(x.card)}\n\nESTIMATED TOTAL: ${money(x.total)}\n\nPrice may change if additional parts, labor, damage, or diagnosis is required.`;$('quoteOut').textContent=out}
function buildInvoice(){const x=totals('inv'),desc=$('invDesc').value;const signed=signatureData()?`\nSIGNATURE: Captured`:'';const out=`INVOICE\n${docContext()}\n\nWORK PERFORMED:\n${desc}\n\nPARTS:\n${partsText()}\n\nLABOR: ${x.h} hrs x ${money(x.r)} = ${money(x.labor)}\nSERVICE CALL: ${money(x.svc)}\nTRAVEL / MILEAGE: ${money(x.travel)}\nPARTS: ${money(x.partsSell)}\nSUBTOTAL: ${money(x.subtotal)}\nTAX: ${money(x.tax)}\nCARD FEE: ${money(x.card)}\n\nTOTAL DUE: ${money(x.total)}${signed}\n\nPayment due upon completion.`;$('invoiceOut').textContent=out;return{x,out}}
function clearQuote(){$('quoteDesc').value='';$('quoteOut').textContent=''} function clearInvoice(){$('invDesc').value='';$('invoiceOut').textContent='';clearSignature()}
function buildWorkOrder(){const out=`WORK ORDER\n${docContext()}\n\nCOMPLAINT:\n${$('woComplaint').value}\n\nDIAGNOSIS:\n${$('woDiagnosis').value}\n\nWORK PERFORMED:\n${$('woWork').value}\n\nNOTES:\n${$('woNotes').value}`;$('woOut').textContent=out}
function clearWorkOrder(){['woComplaint','woDiagnosis','woWork','woNotes'].forEach(id=>$(id).value='');$('woOut').textContent=''}
function sendWOToInvoice(){$('invDesc').value=[$('woDiagnosis').value,$('woWork').value,$('woNotes').value].filter(Boolean).join('\n');show('invoice')}
function writeProfessional(type){let id=type==='quote'?'quoteDesc':type==='invoice'?'invDesc':'woWork';let v=$(id).value.trim();if(!v)return alert('Enter notes first.');$(id).value=v.replace(/\bi\b/g,'I').replace(/\s+/g,' ').trim();if(type==='quote')buildQuote();if(type==='invoice')buildInvoice();if(type==='workorder')buildWorkOrder()}
function textOut(id){const txt=$(id).textContent;if(!txt)return alert('Build it first.');location.href='sms:?&body='+encodeURIComponent(txt)}
function saveInvoiceLocal(){const b=buildInvoice();const list=storage('rw_invoices',[]);list.unshift({date:new Date().toISOString(),total:b.x.total,text:b.out});save('rw_invoices',list);alert('Invoice saved.')}
function clearFinance(){['laborRev','partsProfit','otherExp'].forEach(id=>$(id).value='');$('financeOut').textContent=''}
function loadFinanceFromInvoices(){const list=storage('rw_invoices',[]);$('laborRev').value=list.reduce((s,i)=>s+Number(i.total||0),0).toFixed(2);calcFinance()}
function calcFinance(){const rent=+$('rent').value||0,ins=+$('insurance').value||0,ele=+$('electric').value||0,other=+$('otherExp').value||0,rev=+$('laborRev').value||0,pp=+$('partsProfit').value||0;const exp=rent+ins+ele+other,net=rev+pp-exp;$('financeOut').textContent=`REVENUE: ${money(rev)}\nPARTS PROFIT: ${money(pp)}\nEXPENSES: ${money(exp)}\n\nNET: ${money(net)}\nBREAK-EVEN HOURS @ ${money(getSettings().rate)}/hr: ${(exp/getSettings().rate).toFixed(1)} hrs`}
let drawing=false, ctx2=null;
function setupSig(){const c=$('sig');if(!c)return;ctx2=c.getContext('2d');ctx2.lineWidth=4;ctx2.lineCap='round';ctx2.strokeStyle='#111';const pos=e=>{const r=c.getBoundingClientRect();const p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*(c.width/r.width),y:(p.clientY-r.top)*(c.height/r.height)}};const start=e=>{drawing=true;const p=pos(e);ctx2.beginPath();ctx2.moveTo(p.x,p.y);e.preventDefault()};const move=e=>{if(!drawing)return;const p=pos(e);ctx2.lineTo(p.x,p.y);ctx2.stroke();e.preventDefault()};const end=()=>{drawing=false;localStorage.setItem('rw_signature',c.toDataURL())};['mousedown','touchstart'].forEach(ev=>c.addEventListener(ev,start));['mousemove','touchmove'].forEach(ev=>c.addEventListener(ev,move));['mouseup','mouseleave','touchend'].forEach(ev=>c.addEventListener(ev,end));const d=localStorage.getItem('rw_signature');if(d){const img=new Image();img.onload=()=>ctx2.drawImage(img,0,0);img.src=d}}
function clearSignature(){localStorage.removeItem('rw_signature');if(ctx2)ctx2.clearRect(0,0,$('sig').width,$('sig').height)} function signatureData(){return localStorage.getItem('rw_signature')}
function saveSettings(){const s={shop:$('setShop').value,phone:$('setPhone').value,web:$('setWeb').value,backend:$('setBackend').value,supabaseUrl:$('setSupabaseUrl').value,supabaseKey:$('setSupabaseKey').value,rate:+$('setRate').value||135,service:+$('setService').value||250,markup:+$('setMarkup').value||15,tax:+$('setTax').value||0,card:+$('setCard').value||0,theme:$('setTheme').value};setSettings(s);applySettings();$('settingsOut').textContent='Settings saved.'}
function applySettings(){const s=getSettings();[['setShop','shop'],['setPhone','phone'],['setWeb','web'],['setBackend','backend'],['setSupabaseUrl','supabaseUrl'],['setSupabaseKey','supabaseKey'],['setRate','rate'],['setService','service'],['setMarkup','markup'],['setTax','tax'],['setCard','card'],['setTheme','theme']].forEach(([id,k])=>{if($(id))$(id).value=s[k]??''});['quoteRate','invRate'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=s.rate});['quoteService','invService'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=s.service});['quoteTax','invTax'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=s.tax});['quoteCard','invCard'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=s.card});if($('partMarkup')&&!$('partMarkup').value)$('partMarkup').value=s.markup;if($('rent')&&!$('rent').value)$('rent').value=1500;if($('insurance')&&!$('insurance').value)$('insurance').value=145;if($('electric')&&!$('electric').value)$('electric').value=250;renderDash()}
function resetSettings(){localStorage.removeItem('rw_settings');applySettings()} async function testBackend(){try{const r=await fetch(getSettings().backend);$('settingsOut').textContent='Backend reachable: '+r.status}catch(e){$('settingsOut').textContent='Backend test failed: '+e.message}}
function renderAll(){renderDash();loadTruckFields();loadCustomerFields();renderClocks();renderParts();applySettings()}
window.addEventListener('DOMContentLoaded',()=>{applySettings();renderAll();setupSig();setInterval(renderClocks,1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})});
